name: "Remix deployment"

jobs:
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Cancel previous runs
#        uses: styfle/cancel-workflow-action@0.9.1
#
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
#
#      - name: Install dependencies
#        uses: bahmutov/npm-install@v1
#
#      - name: Arc hydrate
#        run: ./node_modules/.bin/arc hydrate
#
#      - name: Run tests
#        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Env report
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:     $VER"


      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Arc hydrate
        run: ./node_modules/.bin/arc hydrate

      - name: Build
        run: npm run build
      
      - name: Deploy Staging
        if: ${{ inputs.ENV_NAME === "staging" }}
        run: ./node_modules/.bin/arc deploy -v --prune
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Production
        if: ${{ secrets.ENV_NAME === "production" }}
        run: ./node_modules/.bin/arc deploy --production -v --prune
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}